# Generated by Django 5.0.1 on 2024-04-26 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_category_customer_product_delete_employee1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='iamge',
            new_name='image',
        ),
    ]
