# Generated by Django 5.0.1 on 2024-06-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='phone',
            field=models.CharField(default=1, max_length=42),
            preserve_default=False,
        ),
    ]
